export const TECH_STACKS = [
    { icon: "mysql.svg", language: "MySQL" },
    { icon: "influxdb.svg", language: "InfluxDB" },
    { icon: "go.svg", language: "Golang" },
    { icon: "python.svg", language: "Python" },
    { icon: "php.svg", language: "PHP" },
    { icon: "laravel.svg", language: "Laravel" },
    { icon: "gcp.svg", language: "GCP" },
    { icon: "github.svg", language: "GitHub" },
    { icon: "gitlab.svg", language: "GitLab" },
    { icon: "postman.svg", language: "Postman" },
    { icon: "html.svg", language: "HTML" },
    { icon: "css.svg", language: "CSS" },
    { icon: "javascript.svg", language: "JavaScript" },
    { icon: "reactjs.svg", language: "ReactJS" },
    { icon: "tailwind.svg", language: "Tailwind CSS" },
    { icon: "bootstrap.svg", language: "Bootstrap" },
    { icon: "nodejs.svg", language: "Node JS" },
    { icon: "pandas.svg", language: "Pandas" },
    { icon: "jquery.svg", language: "jQuery" },
    { icon: "trello.svg", language: "Trello" },
    { icon: "notion.svg", language: "Notion" },
    { icon: "miro.svg", language: "Miro" },
    { icon: "sonarqube.svg", language: "SonarQube" },
    { icon: "bash.svg", language: "Bash" },
    { icon: "excel.svg", language: "Excel" },
    { icon: "word.svg", language: "Word" },
    { icon: "api.svg", language: "REST API" },
    { icon: "antigravity.svg", language: "Antigravity" },
    { icon: "gin.svg", language: "Gin" },
    { icon: "echo.svg", language: "Echo" },
    { icon: "gorm.svg", language: "Gorm" },
    { icon: "ajax.svg", language: "Ajax" },
];
